config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'welcome#index'

  mount HealthMonitor::Engine, at: '/'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: 'dev/emails'
  end

  concern :with_datatable do
    post 'datatable', on: :collection
  end

  ### All routes below this point should require login or API key ###
  authenticate :user, lambda { |u| u.admin? } do
    mount Logster::Web, at: 'logs'
    mount Sidekiq::Web, at: 'sidekiq'
  end

  devise_for :users, module: 'authentication',
              skip_helpers: [:registrations],
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  as :user do
    get   'my/password', to: 'authentication/registrations#edit',   as: 'edit_user_registration'
    patch 'my/password', to: 'authentication/registrations#update', as: 'user_registration'
  end

  scope 'my' do
    match 'account', to: 'my#account', as: 'my_account', via: [:get, :patch]
  end

  resources :mailing_lists

  namespace :admin do
    root to: 'welcome#index', as: 'root'

    resources :settings, only: [:index]
    resources :users, except: [:show], concerns: [:with_datatable] do
      member do
        get   'change_password'
        patch 'update_password'
      end
    end
  end
end

app/models/mailing_list.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: mailing_lists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text(65535)
#  enabled     :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  email       :string(255)
#
# Indexes
#
#  index_mailing_lists_on_email  (email) UNIQUE
#

class MailingList < ApplicationRecord

  # Relations
  has_many :emails, inverse_of: :mailing_list, dependent: :destroy

  # Validations
  validates :email, uniqueness: true

end

app/controllers/mailing_lists_controller.rb
# frozen_string_literal: true

class MailingListsController < ApplicationController

  responders :flash
  respond_to :html


  def index
    run MailingLists::Index
  end


  def show
    run MailingLists::Show
  end


  def new
    run MailingLists::Create::Present
  end


  def create
    run MailingLists::Create do |result|
      return respond_with result[:model], location: -> { mailing_lists_path }
    end
    render :new
  end


  def edit
    run MailingLists::Update::Present
  end


  def update
    run MailingLists::Update do |result|
      return respond_with result[:model], location: -> { mailing_lists_path }
    end
    render :edit
  end


  def destroy
    run MailingLists::Delete
    respond_with result[:model], location: -> { mailing_lists_path }
  end

end

app/views/mailing_lists/_email_fields.html.haml
%tr.nested-fields
  %td= f.text_field  :first_name, skip_label: true, label_col: '', control_col: 'col-md-12'
  %td= f.text_field  :last_name,  skip_label: true, label_col: '', control_col: 'col-md-12'
  %td= f.email_field :email,      skip_label: true, label_col: '', control_col: 'col-md-12'
  %td= link_to_remove_association icon('trash-o'), f, data: { 'wrapper-class': 'nested-fields' }

app/views/mailing_lists/_form.html.haml
.row
  .col-md-8
    .panel.panel-default
      .panel-heading= @model.name
      .panel-body

        = easy_form_for @form, label_col: 'col-md-2', control_col: 'col-md-10' do |f|

          = f.text_field :name,  required: true
          = f.text_field :email, required: true
          = f.text_area  :description, rows: 5
          = f.form_group do
            = f.check_box :enabled, label: MailingList.human_attribute_name('enabled')

          = link_to_add_association icon('plus', t('.add_email')), f, :emails, data: { 'association-insertion-node': '#nested-fields > tbody', 'association-insertion-position': 'append' }

          .table-responsive
            %table.table{ id: 'nested-fields' }
              %thead
                %tr
                  %th= Email.human_attribute_name('first_name')
                  %th= Email.human_attribute_name('last_name')
                  %th= Email.human_attribute_name('email')
                  %th
              %tbody
                = f.fields_for :emails do |ff|
                  = render 'email_fields', f: ff

          = f.form_group do
            = f.button nil, options_for_spinner_button
            = link_to t('button.cancel'), mailing_lists_path, class: 'btn btn-default'

app/views/mailing_lists/_show.html.haml
.panel.panel-default
  .panel-heading
    = @model.name
    .pull-right
      = MailingList.human_attribute_name('enabled')
      = bool_to_icon @model.enabled?

  .panel-body= @model.description
  %table.table
    %thead
      %tr
        %th= Email.human_attribute_name('first_name')
        %th= Email.human_attribute_name('last_name')
        %th= Email.human_attribute_name('email')
    %tbody
      - @model.emails.each do |email|
        %tr
          %td= email.first_name
          %td= email.last_name
          %td= mail_to email.email

app/views/mailing_lists/edit.html.haml
%h2.page-header= page_title

= render 'form'

app/views/mailing_lists/index.html.haml
%h2.page-header= page_title

.row
  .col-md-6
    .panel.panel-default

      .panel-heading= link_to icon('plus', t('.new')), new_mailing_list_path

      %ul.list-group
        - @model.each do |mailing_list|
          %li.list-group-item
            = link_to "#{mailing_list.name} (#{mailing_list.email})", mailing_list, remote: true
            .pull-right
              = link_to icon('pencil', t('text.edit')), edit_mailing_list_path(mailing_list)
              = link_to icon('trash-o', t('text.delete')), mailing_list_path(mailing_list), method: :delete, data: { confirm: t('text.are_you_sure') }
  .col-md-8
    #mailing-list-renderer

app/views/mailing_lists/new.html.haml
%h2.page-header= page_title

= render 'form'

app/views/mailing_lists/show.js.erb
<%= js_render_partial('#mailing-list-renderer', 'mailing_lists/show') %>