config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'welcome#index'

  mount HealthMonitor::Engine, at: '/'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: 'dev/emails'
  end

  concern :with_datatable do
    post 'datatable', on: :collection
  end

  ### All routes below this point should require login or API key ###
  authenticate :user, lambda { |u| u.admin? } do
    mount Logster::Web, at: 'logs'
    mount Sidekiq::Web, at: 'sidekiq'
  end

  devise_for :users, module: 'authentication',
              skip_helpers: [:registrations],
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  as :user do
    get   'my/password', to: 'authentication/registrations#edit',   as: 'edit_user_registration'
    patch 'my/password', to: 'authentication/registrations#update', as: 'user_registration'
  end

  scope 'my' do
    match 'account', to: 'my#account', as: 'my_account', via: [:get, :patch]
  end

  resources :mailing_lists

  namespace :admin do
    root to: 'welcome#index', as: 'root'

    resources :settings, only: [:index]
    resources :users, except: [:show], concerns: [:with_datatable] do
      member do
        get   'change_password'
        patch 'update_password'
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string(255)
#  last_name              :string(255)
#  language               :string(255)
#  time_zone              :string(255)
#  admin                  :boolean          default(FALSE)
#  enabled                :boolean          default(TRUE)
#  last_request_at        :datetime
#  logged_in              :boolean          default(FALSE)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord

  # Devise stuff (put it first as we may override some methods)
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # Patch Devise for User
  include DeviseForUser

  # Scopes
  scope :order_by_full_name, -> { order({ first_name: :asc, last_name: :asc }) }

  scope :admin,     -> { where(admin: true) }
  scope :non_admin, -> { where(admin: false) }

  scope :active, -> { where(enabled: true) }
  scope :locked, -> { where(enabled: false) }


  def super_admin?
    id == 1
  end

end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < DefaultController

    responders :flash
    respond_to :html
    respond_to :js

    include BaseController::Datatable

    set_datatable_class 'Admin::UserDatatable'


    def index
    end


    def new
      run Admin::Users::Create::Present
    end


    def create
      run Admin::Users::Create do |result|
        return respond_with result[:model], location: -> { admin_users_path }
      end
      render :new
    end


    def edit
      run Admin::Users::Update::Present
    end


    def update
      run Admin::Users::Update do |result|
        reload_user_locales if result[:model].id == current_user.id
        return respond_with result[:model], location: -> { admin_users_path }
      end
      render :edit
    end


    def destroy
      run Admin::Users::Delete
      respond_with result[:model], location: -> { admin_users_path }
    end


    def change_password
      run Admin::Users::Password::Present
    end


    def update_password
      run Admin::Users::Password do |result|
        sign_in(result[:model], bypass: true) if result[:model].id == current_user.id
        return respond_with result[:model], location: -> { admin_users_path }
      end
      render :change_password
    end

  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin
  module UsersHelper

    def user_password_options
      [
        ['generate', ::User.human_attribute_name('generate_password')],
        ['manual',   ::User.human_attribute_name('specify_password')],
      ]
    end

  end
end

app/views/admin/users/_datatable.html.haml
- bootstrap_datatables_for :users,
    ajax:   { url: datatable_admin_users_path(format: :json), type: 'POST' },
    dom:    datatable_dom_with_selected_and_buttons,
    order:  [[ 0, 'asc' ]] do |t|

  - t.js_method 'createDatatableWithButtons'

  - t.button datatable_button_for('reset_filters')

  - t.button datatable_button_for('csv')
  - t.button datatable_button_for('excel')
  - t.button datatable_button_for('pdf')
  - t.button datatable_button_for('print')

  - t.head_for :first_name,      label: User.human_attribute_name('first_name')
  - t.head_for :email,           label: User.human_attribute_name('email')
  - t.head_for :admin,           label: User.human_attribute_name('admin')
  - t.head_for :last_sign_in_at, label: User.human_attribute_name('last_connection')
  - t.head_for :actions,         label: t('text.actions'), sortable: false
  - t.head_for :enabled,         label: User.human_attribute_name('enabled'), visible: false
  - t.body

  = t.search_form url: admin_users_path, method: :get, layout: :horizontal do |f|
    = hidden_field_tag 'ids[]'
    .row
      .col-md-3= f.search_field :first_name
      .col-md-3= f.select :admin
      .col-md-3= f.select :enabled

  = t.render_datatable
  - content_for :javascript do
    = t.render_js_datatable

app/views/admin/users/_form.html.haml
%h2.page-header= page_title

= easy_form_for [:admin, @form], label_col: 'col-md-4', control_col: 'col-md-8' do |f|
  .row
    .col-md-6
      .panel.panel-default
        .panel-heading
          = icon 'info', t('text.infos')
          .pull-right
            = link_to icon('lock', t('.change_password')), change_password_admin_user_path(@model) unless @model.new_record?

        .panel-body
          = f.text_field  :first_name, required: true
          = f.text_field  :last_name,  required: true
          = f.email_field :email,      required: true, label_class: 'required'

          = f.select           :language, available_locales, selected: (@model.language.present? ? @model.language : I18n.default_locale)
          = f.time_zone_select :time_zone, nil, { default: 'Paris' }

          - unless @model.super_admin?
            = f.form_group label: { text: User.human_attribute_name('admin') } do
              = f.check_box :admin, label: ''

          - unless @model.super_admin?
            = f.form_group label: { text: User.human_attribute_name('enabled') } do
              = f.check_box :enabled, label: ''

          - if @model.new_record?
            = render 'password_fields', f: f

          = f.form_group do
            = f.button nil, options_for_spinner_button
            = link_to t('button.cancel'), admin_users_path, class: 'btn btn-default'

app/views/admin/users/_password_fields.html.haml
#select-password-creation-mode
  = f.hidden_field :create_options, value: ''
  = f.collection_radio_buttons :create_options, user_password_options, :first, :last, inline: false, control_col: 'col-md-6'

#password-manual-creation{ style: display_on_condition(f.object.create_options, 'manual') }
  = f.password_field :password, autocomplete: 'off', control_col: 'col-md-4', required: false
  = f.password_field :password_confirmation, autocomplete: 'off', control_col: 'col-md-4', required: false

= f.form_group do
  = f.check_box :send_by_mail, label: User.human_attribute_name('send_by_mail')

- content_for :javascript do
  :plain
    $('#select-password-creation-mode input:radio').on('change', function(){
      value = $("#select-password-creation-mode input[type='radio']:checked").val();
      if (value == 'manual'){
        $('#password-manual-creation').show();
      } else {
        $('#password-manual-creation').hide();
      }
    });

app/views/admin/users/change_password.html.haml
%h2.page-header= page_title

.panel.panel-default
  .panel-body
    = easy_form_for [:admin, @form], url: update_password_admin_user_path(@model), label_col: 'col-md-2', control_col: 'col-md-4' do |f|

      = render 'password_fields', f: f

      = f.form_group do
        = f.button nil, options_for_spinner_button
        = link_to t('button.cancel'), edit_admin_user_path(@model), class: 'btn btn-default'

app/views/admin/users/destroy.js.erb
$("#users-datatable").DataTable().ajax.reload();
<%= render_flashes_as_js %>

app/views/admin/users/edit.html.haml
= render 'form'

app/views/admin/users/index.html.haml
%h2.page-header= page_title

.panel.panel-default
  .panel-heading
    = link_to icon('plus', t('.add_user')), new_admin_user_path
  .panel-body
    = render 'datatable'

app/views/admin/users/new.html.haml
= render 'form'